version: '3.6'

networks:
  frontend:
  backend:

volumes:
  db:
    external:
      name: app_db
  storage:
    external:
      name: app_storage

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - ./src:/app
      - storage:/app/storage
    networks:
      - backend
    expose:
      - 3000
    #environment:
    #  - RAILS_MASTER_KEY=
    depends_on:
      - db

  server:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - frontend
      - backend
    expose:
      - 80
    depends_on:
      - app

  db:
    image: postgres:10.3
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    expose:
      - 5432