version: '3.6'

networks:
  frontend:
  backend:

volumes:
  db:
  db_admin:
  storage:
  portainer:

services:
  server:
    build: ./nginx
    env_file:
      - ./env/common.env
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - frontend
      - backend
    expose:
      - 80
    depends_on:
      - app

  app:
    build: .
    env_file:
      - ./env/common.env
    volumes:
      - ./src:/app
      - storage:/app/storage
    networks:
      - backend
    expose:
      - 3000
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    env_file:
      - ./env/common.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    expose:
      - 5432

  db_admin:
    image: dpage/pgadmin4
    env_file:
      - ./env/common.env
    networks:
      - frontend
      - backend
    volumes:
      - db_admin:/var/lib/pgadmin
    expose:
      - 80
    depends_on:
      - db

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    expose:
      - 9000