version: '3.6'

services:
  app:
    restart: "no"
    ports:
      - "3000:3000"

  db_admin:
    image: dpage/pgadmin4
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - backend
    volumes:
      - ./src/tmp/pgadmin:/var/lib/pgadmin
    ports:
      - "8000:80"
